[package]
name = "ferric_ftp"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
ssh2 = "0.9.5"
chrono = "0.4.41"
log = "0.4.27"
env_logger = "0.11.8"

[[test]]
name = "integration"
path = "tests/integration/mod.rs"
